### ISSUE TITLE
Hide/Remove Execution Plans tab

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-ui#222]
Having empty page is just not a good UX. I don't know why it is there at all. It only confuses users.

![Screenshot 2023-01-13 at 9 37 18](https://user-images.githubusercontent.com/5530211/212275354-b9b20135-9b5e-454e-8f35-1751f2b43b55.png)

@korel-san @wajda Any thoughts?

**Comment by wajda** [comment]
It contradicts the issue #211

**Comment by cerveada** [comment]
> It contradicts the issue https://github.com/AbsaOSS/spline-ui/issues/211

Not really. Once the 211 is implemented the tab will be there of course. But we should not released any more versions with empty tab.

**Comment by wajda** [comment]
Sure. I realized #211 was not assigned to 1.0.0 release, so I updated it.
