### ISSUE TITLE
Incorrect 404 error message

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-ui#61]
When the `/lineage-detailed` REST returns 404 the page says there was an error. It should say "not found" instead.

![image](https://user-images.githubusercontent.com/795479/109404955-83862400-796b-11eb-8dab-305350ba8fbc.png)

**Comment by oleksandr-korchak** [comment]
@wajda  as agreed no redirection to the 404 page will be provided, but the error will be processed in a generic way: 
* Main Message changed from "Unexpected server error" to "Not Found" in case if response status code === 404.
