### ISSUE TITLE
Missing punctuation in Expression rendering

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-ui#63]
![image](https://user-images.githubusercontent.com/795479/109784325-43dd6780-7c0b-11eb-8a48-dc6b94131355.png)

**Comment by oleksandr-korchak** [comment]
![image.png](https://images.zenhubusercontent.com/5e84abe0841402686c6b6d55/fdf80b7b-6916-49c4-aa2b-7f7afc84323b)

**Comment by oleksandr-korchak** [comment]
Default rendering rules for all expressions of type **'expr.Generic'** was changed to:

`leafText + join(childrenTexts, ', ') => ${leafText}(${join(childrenTexts, ', ')})`

So, from now all children will be displayed in braces for that type of expression like so:

![image.png](https://images.zenhubusercontent.com/5e84abe0841402686c6b6d55/45ef852f-8456-4b18-a6e7-33ece5413b86)
