### ISSUE TITLE
Error message: replace "unexpected server error" with "server is unavailable" in case of disconnection

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-ui#80]
![image](https://user-images.githubusercontent.com/795479/111000831-0c955600-8383-11eb-8c41-274adb6c9818.png)

**Comment by oleksandr-korchak** [comment]
@wajda done, it is in dev now.

**Comment by wajda** [comment]
Another case - this message seems to pop up on JS errors as well. For instance when the server returns a node with `name: null` (valid response) this error message pops up. And there is no error logs in the browser console, which makes it extremely difficult to figure out what's going on.
