### ISSUE TITLE
Overview graph: Missing execution node details

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-ui#90]
![image](https://user-images.githubusercontent.com/795479/114017604-82022280-986c-11eb-8c08-927dd8fe6082.png)

While the old UI gives more info:

![image](https://user-images.githubusercontent.com/795479/114017791-bb3a9280-986c-11eb-9b61-83a5dd8c754a.png)

**Comment by oleksandr-korchak** [comment]
@wajda to get that information we need to fetch extra data from the BE, but we do not have a simple route for Execution Plan details, but we need to use the route with the calculation of execution plan lineage, etc. It is kind of overkill to trigger all these calculations just to get some static information from there.

Also, I would not display data about Input/Output DataSources as it is not consistent with the information about relevant graph DataSource nodes where we have only the information about the URL. So, if we know information about inputs of some Execution Plan and want to display it here, it is better to make it a part of the graph => Input DataSources nodes will be displayed at graph => the information about input DS will be displayed in the parent nodes section.

I would suggest solving that task after the relevant API route will be implemented. It is easy and fast to implement that API endpoint, it can be a good candidate for the next minor release.

**Comment by wajda** [comment]
I'll add system and agent info to the node itself, so no extra XHR is needed.
Input/Output info is the same URIs that you display in the parent/children tabs, but just displayed in one place for better discoverability.

**Comment by oleksandr-korchak** [comment]
> I'll add system and agent info to the node itself, so no extra XHR is needed.
> Input/Output info is the same URIs that you display in the parent/children tabs, but just displayed in one place for better discoverability.

There is no problem with having an extra API request, but just with the fact, that causes unnecessary extra calculation. If you have room for some work according to that task in the current version, then it would be better to implement the route `/execution-plans/{executionPlanId}` according to the API proposal v2.3.SNAPSHOT.

As I have mentioned before, we do not have data about inputs in graph data for some nodes (edge case, the first shown Execution node doe not have inputs). So, it is not enough just to add system/agent Info, we need also information about inputs. According to me, it is not a good idea to add that information to the Execution node, it is better to extend the graph data. 

So, we have 2 options now:

- do it in a proper way by implementing the new endpoint
- do it ad-hock way by extending graph node data by extra data (system/agent info) + add extra DataSource nodes (Execution Inputs for edge cases).

I think, that if we want to display information about the inputs for each Execution node and we want to be consistent it is better to implement calculations of extra input DataSources nodes in both cases.

**Comment by oleksandr-korchak** [comment]
@wajda we also can ignore the edge case for now, and do not display information about Inputs for the relevant Execution if we do not know it from the graph relations data.
