### ISSUE TITLE
Show Git commit ID (revision) in addition to the version info

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-ui#97]
Add two constants that can be defined during NPM build, e.g. passed as environment variables:

- `SPLINE_UI_BUILD_REVISION`
- `SPLINE_UI_BUILD_TIMESTAMP`

The above constants would hold the build meta info that is to be displayed on the web page in addition to the version number.
Both variables are optional.

Display example:
```
Spline 1.2.3
Apr 16, 2021
rev. 1234567
```

(ref: AbsaOSS/spline#866)

**Comment by oleksandr-korchak** [comment]
![image.png](https://images.zenhubusercontent.com/5e84abe0841402686c6b6d55/142831aa-6ba7-4dce-9e25-cf1ae37ab72c)
